# Generated by Django 4.1.3 on 2022-11-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    correspondencia_estado =[
    (1,'Entregado'),
    (2,'En envio'),
    (3,'No entregado')
]

    operations = [
        migrations.CreateModel(
            name='correspondencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recepcion', models.CharField(max_length=30)),
                ('conserjeremitente', models.CharField(max_length=30)),
                ('destinatario', models.CharField(max_length=30)),
                ('estado', models.IntegerField(
        null=False ,blank=False,
        choices=correspondencia_estado,
        default=1
        )) ,
            ],
        ),
        migrations.CreateModel(
            name='residencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_res', models.CharField(max_length=30)),
                ('dueño_res', models.CharField(max_length=30)),
                ('fono_dueño', models.CharField(max_length=30)),
                ('email_dueño', models.CharField(max_length=30)),
            ],
        ),
    ]
