# Generated by Django 4.1.3 on 2022-11-13 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='correspondencia',
            old_name='conserjeremitente',
            new_name='conserje_remitente',
        ),
    ]
